server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
      - id: greetingModule
        uri: http://localhost:8082/
        predicates:
        - Path=/greeting/**
      - id: feignClientModule
        uri: http://localhost:8083/
        predicates:
        - Path=/get-greeting/**